(()=>{
const P={
'reports-section':{k:'DELIVERY ANALYTICS',t:'Reports (Send SMS)',d:'Track every outgoing message, delivery result and API activity.',action:'Export Report',stats:[['Total Sent','124,580','↗ 12.4%'],['Delivered','118,450','↗ 15.6%'],['Failed','6,130','↘ 2.3%'],['Pending','2,000','↗ 1.2%']],cols:['#','Mobile Number','Message','Channel','Status','Date & Time','Action']},
'msg-report-section':{k:'MESSAGE REPORT',t:'Msg Report',d:'Detailed message-level reporting with quick filters and status tracking.',action:'Download CSV',stats:[['Today','3,248','Messages'],['Success Rate','95.1%','Excellent'],['Failed','138','Needs attention'],['Avg. Delay','1.8s','Fast']],cols:['ID','Recipient','Message','Account','Status','Sent At','Delivery']},
'campaigns-section':{k:'CAMPAIGN CENTER',t:'Campaigns',d:'Create, monitor and manage bulk WhatsApp messaging campaigns.',action:'+ New Campaign',stats:[['Active Campaigns','12','Running'],['Completed','248','This month'],['Scheduled','18','Upcoming'],['Reach','98.4K','Recipients']],cols:['Campaign','Recipients','Account','Progress','Status','Created','Action']},
'templates-section':{k:'MESSAGE LIBRARY',t:'Templates',d:'Save reusable messages with variables, media and quick actions.',action:'+ Create Template',stats:[['Total Templates','42','Saved'],['Active','38','Ready to use'],['Media Templates','14','Rich media'],['Used This Month','1,842','Messages']],cols:['Template','Category','Preview','Variables','Used','Updated','Action']},
'numbers-section':{k:'WHATSAPP SESSIONS',t:'Numbers',d:'Manage connected WhatsApp numbers, sessions, QR pairing and health.',action:'+ Add Number',stats:[['Connected','12','Online'],['Connecting','1','Pairing'],['Disconnected','2','Offline'],['Messages Today','3,248','Across all']],cols:['Number','Account','Session','Messages','Health','Last Active','Action']}
};
const rows={
'reports-section':[['1','+91 98765 43210','Recharge confirmation sent','WhatsApp','Success','10 Sep 2026, 10:30 AM','View'],['2','+91 98123 45678','Your payment was received','WhatsApp','Success','10 Sep 2026, 10:22 AM','View'],['3','+91 87654 32109','Offer message delivered','API','Pending','10 Sep 2026, 10:18 AM','View'],['4','+91 91234 56789','Account alert notification','WhatsApp','Failed','10 Sep 2026, 10:11 AM','View']],
'msg-report-section':[['MSG-10425','+91 98765 43210','Order confirmation','Prince Goyal','Delivered','10:30 AM','✓✓'],['MSG-10424','+91 98123 45678','Payment received','Business','Delivered','10:22 AM','✓✓'],['MSG-10423','+91 87654 32109','Special offer','Prince Goyal','Pending','10:18 AM','—'],['MSG-10422','+91 91234 56789','Account alert','Support','Failed','10:11 AM','×']],
'campaigns-section':[['September Offer','12,500','Prince Goyal','78%','Running','09 Sep 2026','Open'],['Recharge Reminder','4,820','Business','100%','Completed','08 Sep 2026','Open'],['New User Welcome','1,240','Support','42%','Running','10 Sep 2026','Open'],['Festival Promo','25,000','Prince Goyal','0%','Scheduled','12 Sep 2026','Open']],
'templates-section':[['Recharge Success','Transactional','Recharge of {{amount}} successful.','amount,number','1,245','Today','Edit'],['Payment Reminder','Reminder','Hello {{name}}, your payment is pending.','name','382','Yesterday','Edit'],['Offer Promo','Marketing','Get our latest offer today!','name,offer','215','08 Sep','Edit'],['Welcome','Utility','Welcome to Easy Recharge, {{name}}.','name','84','07 Sep','Edit']],
'numbers-section':[['+91 98765 43210','Prince Goyal','● Connected','1,248','Healthy','Just now','Manage'],['+91 98123 45678','Business Account','● Connected','842','Healthy','1 min ago','Manage'],['+91 91234 56789','Support Account','● Connected','625','Healthy','3 min ago','Manage'],['+91 87654 32109','Campaign','○ Disconnected','0','Offline','2 hrs ago','Reconnect']]
};
function page(id){const p=P[id];if(!p)return;const stat=p.stats.map((s,i)=>`<article class="pp-stat"><div class="pp-stat-icon">${['✦','✓','◈','◉'][i]}</div><small>${s[0]}</small><strong>${s[1]}</strong><span>${s[2]}</span></article>`).join('');const body=(rows[id]||[]).map((r,i)=>`<tr>${r.map((c,j)=>j===4?`<td><span class="pp-status ${String(c).toLowerCase().includes('success')||String(c).toLowerCase().includes('deliver')||String(c).includes('Connected')?'ok':String(c).toLowerCase().includes('fail')||String(c).includes('Offline')?'bad':'wait'}">${c}</span></td>`:j===r.length-1?`<td><button class="pp-mini-btn">${c}</button></td>`:`<td>${c}</td>`).join('')}</tr>`).join('');return `<div class="pp-page"><div class="pp-hero"><div><span class="section-kicker">${p.k}</span><h2>${p.t}</h2><p>${p.d}</p></div><button class="pp-primary">${p.action}</button></div><div class="pp-stats">${stat}</div><div class="pp-toolbar"><div class="pp-search">⌕ <input placeholder="Search ${p.t.toLowerCase()}..."></div><select><option>All Status</option><option>Success</option><option>Pending</option><option>Failed</option></select><select><option>This Month</option><option>Today</option><option>Last 7 Days</option></select><button class="pp-filter">⚙ Filters</button></div><article class="pp-table-card"><div class="pp-table-head"><div><h3>${p.t} Overview</h3><p>Showing latest activity and records</p></div><span class="pp-live"><i></i> Live data</span></div><div class="pp-table-wrap"><table><thead><tr>${p.cols.map(c=>`<th>${c}</th>`).join('')}</tr></thead><tbody>${body}</tbody></table></div><div class="pp-pagination"><span>Showing 1–4 of 248 records</span><div><button>‹</button><button class="active">1</button><button>2</button><button>3</button><button>›</button></div></div></article></div>`}
function mount(){Object.keys(P).forEach(id=>{const el=document.getElementById(id);if(el&&!el.dataset.pp){el.innerHTML=page(id);el.dataset.pp='1'}});}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',mount);else mount();
window.addEventListener('click',e=>{const b=e.target.closest('.pp-primary,.pp-mini-btn,.pp-filter');if(!b)return;const old=b.textContent;b.textContent=b.classList.contains('pp-primary')?'✓ Ready':'✓';setTimeout(()=>b.textContent=old,900)});
})();